# Generated by Django 5.0.1 on 2024-02-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aviion',
            fields=[
                ('num_avion', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_avion', models.CharField(max_length=100)),
                ('autonomie_avion', models.FloatField()),
                ('capacite_economique', models.IntegerField(default=1)),
                ('capacite_affaire', models.IntegerField(default=1)),
                ('capacite_1er_classe', models.IntegerField(default=1)),
                ('prix_km_economique', models.FloatField(default=1)),
                ('prix_km_affaire', models.FloatField(default=1)),
                ('prix_km_1er_classe', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'avion',
            },
        ),
        migrations.CreateModel(
            name='categoriee',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='vool',
            fields=[
                ('num_vol', models.IntegerField(primary_key=True, serialize=False)),
                ('date_vol', models.DateField()),
                ('heure_depart', models.TimeField()),
            ],
            options={
                'db_table': 'vol',
            },
        ),
        migrations.CreateModel(
            name='passsager',
            fields=[
                ('ID_passager', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_passager', models.CharField(max_length=100)),
                ('prenom_passager', models.CharField(max_length=100)),
                ('email_passager', models.EmailField(max_length=100)),
                ('num_telephone_passager', models.IntegerField()),
                ('fk_idcategorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.categoriee')),
            ],
            options={
                'db_table': 'passager',
            },
        ),
        migrations.CreateModel(
            name='trajeet',
            fields=[
                ('id_trajet', models.AutoField(primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrive', models.CharField(max_length=100)),
                ('prix_trajet_economique', models.FloatField(default=1)),
                ('prix_trajet_affaire', models.FloatField(default=1)),
                ('prix_trajet_1er_classe', models.FloatField(default=1)),
                ('duree_trajet', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('latitude_depart', models.FloatField(null=True)),
                ('longitude_depart', models.FloatField(null=True)),
                ('latitude_arrive', models.FloatField(null=True)),
                ('longitude_arrive', models.FloatField(null=True)),
                ('fk_idavion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.aviion')),
                ('fk_idvol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.vool')),
            ],
            options={
                'db_table': 'trajet',
            },
        ),
        migrations.CreateModel(
            name='reservatiion',
            fields=[
                ('num_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('prix_totale', models.FloatField()),
                ('date_reservation', models.DateField()),
                ('heure_reservation', models.TimeField()),
                ('nbr_passager', models.IntegerField()),
                ('fk_passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.passsager')),
                ('fk_nvol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.vool')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
